<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipalities = [
            'Aguascalientes' => [
                'Aguascalientes',
                'Asientos',
                'Calvillo',
                'Cosío',
                'Jesús María',
                'Pabellón de Arteaga',
                'Rincón de Romos',
                'San Francisco de los Romo',
                'Tepezalá',
                'El Llano'
            ],
            'Baja California' => [
                'Ensenada',
                'Mexicali',
                'Tecate',
                'Tijuana',
                'Playas de Rosarito',
                'San Quintín',
                'San Felipe'
            ],
            'Baja California Sur' => [
                'Comondú',
                'La Paz',
                'Loreto',
                'Los Cabos',
                'Mulegé'
            ],
            'Campeche' => [
                'Calkiní',
                'Campeche',
                'Carmen',
                'Champotón',
                'Hecelchakán',
                'Hopelchén',
                'Palizada',
                'Tenabo',
                'Escárcega',
                'Calakmul',
                'Candelaria',
                'Seybaplaya',
                'Dzitbalché'
            ],
            'Chiapas' => [
                'Acacoyagua',
                'Acala',
                'Acapetahua',
                'Aldama',
                'Altamirano',
                'Amatán',
                'Amatenango de la Frontera',
                'Amatenango del Valle',
                'Ángel Albino Corzo',
                'Arriaga',
                'Bejucal de Ocampo',
                'Bella Vista',
                'Benemérito de las Américas',
                'Berriozábal',
                'Bochil',
                'El Bosque',
                'Cacahoatán',
                'Catazajá',
                'Chalchihuitán',
                'Chamula',
                'Chanal',
                'Chapultenango',
                'Chenalhó',
                'Chiapa de Corzo',
                'Chiapilla',
                'Chicoasén',
                'Chicomuselo',
                'Chilón',
                'Cintalapa',
                'Coapilla',
                'Comitán de Domínguez',
                'La Concordia',
                'Copainalá',
                'Escuintla',
                'Francisco León',
                'Frontera Comalapa',
                'Frontera Hidalgo',
                'La Grandeza',
                'Huehuetán',
                'Huixtán',
                'Huitiupán',
                'Huixtla',
                'La Independencia',
                'Ixhuatán',
                'Ixtacomitán',
                'Ixtapa',
                'Ixtapangajoya',
                'Jiquipilas',
                'Jitotol',
                'Juárez',
                'Larráinzar',
                'La Libertad',
                'Las Margaritas',
                'Las Rosas',
                'Mapastepec',
                'Maravilla Tenejapa',
                'Marqués de Comillas',
                'Mazapa de Madero',
                'Mazatán',
                'Metapa',
                'Mitontic',
                'Montecristo de Guerrero',
                'Motozintla',
                'Nicolás Ruíz',
                'Ocosingo',
                'Ocotepec',
                'Ocozocoautla de Espinosa',
                'Ostuacán',
                'Osumacinta',
                'Oxchuc',
                'Palenque',
                'Pantelhó',
                'Pantepec',
                'Pichucalco',
                'Pijijiapan',
                'El Porvenir',
                'Pueblo Nuevo Solistahuacán',
                'Rayón',
                'Reforma',
                'Sabanilla',
                'Salto de Agua',
                'San Andrés Duraznal',
                'San Cristóbal de las Casas',
                'San Fernando',
                'San Juan Cancuc',
                'San Lucas',
                'Santiago el Pinar',
                'Siltepec',
                'Simojovel',
                'Sitalá',
                'Socoltenango',
                'Solosuchiapa',
                'Soyaló',
                'Suchiapa',
                'Suchiate',
                'Sunuapa',
                'Tapachula',
                'Tapalapa',
                'Tapilula',
                'Tecpatán',
                'Tenejapa',
                'Teopisca',
                'Tila',
                'Tonalá',
                'Totolapa',
                'La Trinitaria',
                'Tumbalá',
                'Tuxtla Chico',
                'Tuxtla Gutiérrez',
                'Tuzantán',
                'Tzimol',
                'Unión Juárez',
                'Venustiano Carranza',
                'Villa Comaltitlán',
                'Villa Corzo',
                'Villaflores',
                'Yajalón',
                'Zinacantán'
            ],
            'Chihuahua' => [
                'Ahumada',
                'Aldama',
                'Allende',
                'Aquiles Serdán',
                'Ascensión',
                'Bachíniva',
                'Balleza',
                'Batopilas',
                'Bocoyna',
                'Buenaventura',
                'Camargo',
                'Carichí',
                'Casas Grandes',
                'Coronado',
                'Coyame del Sotol',
                'La Cruz',
                'Cuauhtémoc',
                'Cusihuiriachi',
                'Chihuahua',
                'Chínipas',
                'Delicias',
                'Dr. Belisario Domínguez',
                'Galeana',
                'Santa Isabel',
                'Gómez Farías',
                'Gran Morelos',
                'Guachochi',
                'Guadalupe',
                'Guadalupe y Calvo',
                'Guazapares',
                'Guerrero',
                'Hidalgo del Parral',
                'Huejotitán',
                'Ignacio Zaragoza',
                'Janos',
                'Jiménez',
                'Juárez',
                'Julimes',
                'López',
                'Madera',
                'Maguarichi',
                'Manuel Benavides',
                'Matachí',
                'Matamoros',
                'Meoqui',
                'Morelos',
                'Moris',
                'Namiquipa',
                'Nonoava',
                'Nuevo Casas Grandes',
                'Ocampo',
                'Ojinaga',
                'Práxedis G. Guerrero',
                'Riva Palacio',
                'Rosales',
                'Rosario',
                'San Francisco de Borja',
                'San Francisco de Conchos',
                'San Francisco del Oro',
                'Santa Bárbara',
                'Satevó',
                'Saucillo',
                'Temósachic',
                'El Tule',
                'Urique',
                'Uruachi',
                'Valle de Zaragoza'
            ],
            'Ciudad de México' => [
                'Álvaro Obregón',
                'Azcapotzalco',
                'Benito Juárez',
                'Coyoacán',
                'Cuajimalpa de Morelos',
                'Cuauhtémoc',
                'Gustavo A. Madero',
                'Iztacalco',
                'Iztapalapa',
                'Magdalena Contreras',
                'Miguel Hidalgo',
                'Milpa Alta',
                'Tláhuac',
                'Tlalpan',
                'Venustiano Carranza',
                'Xochimilco'
            ],
            'Coahuila' => [
                'Abasolo',
                'Acuña',
                'Allende',
                'Arteaga',
                'Candela',
                'Castaños',
                'Cuatrociénegas',
                'Escobedo',
                'Francisco I. Madero',
                'Frontera',
                'General Cepeda',
                'Guerrero',
                'Hidalgo',
                'Jiménez',
                'Juárez',
                'Lamadrid',
                'Matamoros',
                'Monclova',
                'Morelos',
                'Múzquiz',
                'Nadadores',
                'Nava',
                'Ocampo',
                'Parras',
                'Piedras Negras',
                'Progreso',
                'Ramos Arizpe',
                'Sabinas',
                'Sacramento',
                'Saltillo',
                'San Buenaventura',
                'San Juan de Sabinas',
                'San Pedro',
                'Sierra Mojada',
                'Torreón',
                'Viesca',
                'Villa Unión',
                'Zaragoza'
            ],
            'Colima' => [
                'Colima',
                'Comala',
                'Coquimatlán',
                'Cuauhtémoc',
                'Ixtlahuacán',
                'Manzanillo',
                'Minatitlán',
                'Tecomán',
                'Villa de Álvarez'
            ],
            'Durango' => [
                'Canatlán',
                'Canelas',
                'Coneto de Comonfort',
                'Cuencamé',
                'Durango',
                'General Simón Bolívar',
                'Gómez Palacio',
                'Guadalupe Victoria',
                'Guanaceví',
                'Hidalgo',
                'Indé',
                'Lerdo',
                'Mapimí',
                'Mezquital',
                'Nazas',
                'Nombre de Dios',
                'Nuevo Ideal',
                'Ocampo',
                'El Oro',
                'Otáez',
                'Pánuco de Coronado',
                'Peñón Blanco',
                'Poanas',
                'Pueblo Nuevo',
                'Rodeo',
                'San Bernardo',
                'San Dimas',
                'San Juan de Guadalupe',
                'San Juan del Río',
                'San Luis del Cordero',
                'San Pedro del Gallo',
                'Santa Clara',
                'Santiago Papasquiaro',
                'Súchil',
                'Tamazula',
                'Tepehuanes',
                'Tlahualilo',
                'Topia',
                'Vicente Guerrero'
            ],
            'Estado de México' => [
                'Acambay de Ruíz Castañeda',
                'Acolman',
                'Aculco',
                'Almoloya de Alquisiras',
                'Almoloya de Juárez',
                'Almoloya del Río',
                'Amanalco',
                'Amatepec',
                'Amecameca',
                'Apaxco',
                'Atenco',
                'Atizapán',
                'Atizapán de Zaragoza',
                'Atlacomulco',
                'Atlautla',
                'Axapusco',
                'Ayapango',
                'Calimaya',
                'Capulhuac',
                'Coacalco de Berriozábal',
                'Coatepec Harinas',
                'Cocotitlán',
                'Coyotepec',
                'Cuautitlán',
                'Cuautitlán Izcalli',
                'Chalco',
                'Chapa de Mota',
                'Chapultepec',
                'Chiautla',
                'Chicoloapan',
                'Chiconcuac',
                'Chimalhuacán',
                'Donato Guerra',
                'Ecatepec de Morelos',
                'Ecatzingo',
                'Huehuetoca',
                'Hueypoxtla',
                'Huixquilucan',
                'Isidro Fabela',
                'Ixtapaluca',
                'Ixtapan de la Sal',
                'Ixtapan del Oro',
                'Ixtlahuaca',
                'Xalatlaco',
                'Jaltenco',
                'Jilotepec',
                'Jilotzingo',
                'Jiquipilco',
                'Jocotitlán',
                'Joquicingo',
                'Juchitepec',
                'Lerma',
                'Malinalco',
                'Melchor Ocampo',
                'Metepec',
                'Mexicaltzingo',
                'Morelos',
                'Naucalpan de Juárez',
                'Nezahualcóyotl',
                'Nextlalpan',
                'Nicolás Romero',
                'Nopaltepec',
                'Ocoyoacac',
                'Ocuilan',
                'El Oro',
                'Otumba',
                'Otzoloapan',
                'Otzolotepec',
                'Ozumba',
                'Papalotla',
                'La Paz',
                'Polotitlán',
                'Rayón',
                'San Antonio la Isla',
                'San Felipe del Progreso',
                'San Martín de las Pirámides',
                'San Mateo Atenco',
                'San Simón de Guerrero',
                'Santo Tomás',
                'Soyaniquilpan de Juárez',
                'Sultepec',
                'Tecámac',
                'Tejupilco',
                'Temamatla',
                'Temascalapa',
                'Temascalcingo',
                'Temascaltepec',
                'Temoaya',
                'Tenancingo',
                'Tenango del Aire',
                'Tenango del Valle',
                'Teoloyucan',
                'Teotihuacán',
                'Tepetlaoxtoc',
                'Tepetlixpa',
                'Tepotzotlán',
                'Tequixquiac',
                'Texcaltitlán',
                'Texcalyacac',
                'Texcoco',
                'Tezoyuca',
                'Tianguistenco',
                'Timilpan',
                'Tlalmanalco',
                'Tlalnepantla de Baz',
                'Tlatlaya',
                'Toluca',
                'Tonatico',
                'Tonanitla',
                'Tultepec',
                'Tultitlán',
                'Valle de Bravo',
                'Valle de Chalco Solidaridad',
                'Villa de Allende',
                'Villa del Carbón',
                'Villa Guerrero',
                'Villa Victoria',
                'Xonacatlán',
                'Zacazonapan',
                'Zacualpan',
                'Zinacantepec',
                'Zumpahuacán',
                'Zumpango',
                'Luvianos',
                'San José del Rincón',
                'Tonanitla'
            ],
            'Guanajuato' => [
                'Abasolo',
                'Acámbaro',
                'San Miguel de Allende',
                'Apaseo el Alto',
                'Apaseo el Grande',
                'Atarjea',
                'Celaya',
                'Manuel Doblado',
                'Comonfort',
                'Coroneo',
                'Cortazar',
                'Cuerámaro',
                'Doctor Mora',
                'Dolores Hidalgo Cuna de la Independencia Nacional',
                'Guanajuato',
                'Huanímaro',
                'Irapuato',
                'Jaral del Progreso',
                'Jerécuaro',
                'León',
                'Moroleón',
                'Ocampo',
                'Pénjamo',
                'Pueblo Nuevo',
                'Purísima del Rincón',
                'Romita',
                'Salamanca',
                'Salvatierra',
                'San Diego de la Unión',
                'San Felipe',
                'San Francisco del Rincón',
                'San José Iturbide',
                'San Luis de la Paz',
                'Santa Catarina',
                'Santa Cruz de Juventino Rosas',
                'Santiago Maravatío',
                'Silao de la Victoria',
                'Tarandacuao',
                'Tarimoro',
                'Tierra Blanca',
                'Uriangato',
                'Valle de Santiago',
                'Victoria',
                'Villagrán',
                'Xichú',
                'Yuriria'
            ],
            'Guerrero' => [
                'Acapulco de Juárez',
                'Ahuacuotzingo',
                'Ajuchitlán del Progreso',
                'Alcozauca de Guerrero',
                'Alpoyeca',
                'Apaxtla de Castrejón',
                'Arcelia',
                'Atenango del Río',
                'Atlamajalcingo del Monte',
                'Atlixtac',
                'Atoyac de Álvarez',
                'Ayutla de los Libres',
                'Azoyú',
                'Benito Juárez',
                'Buenavista de Cuéllar',
                'Coahuayutla de José María Izazaga',
                'Cocula',
                'Copala',
                'Copalillo',
                'Copanatoyac',
                'Coyuca de Benítez',
                'Coyuca de Catalán',
                'Cuajinicuilapa',
                'Cualác',
                'Cuautepec',
                'Cuetzala del Progreso',
                'Cutzamala de Pinzón',
                'Chilapa de Álvarez',
                'Chilpancingo de los Bravo',
                'Florencio Villarreal',
                'General Canuto A. Neri',
                'General Heliodoro Castillo',
                'Huamuxtitlán',
                'Huitzuco de los Figueroa',
                'Iguala de la Independencia',
                'Igualapa',
                'Ixcateopan de Cuauhtémoc',
                'José Joaquín de Herrera',
                'Juan R. Escudero',
                'Leonardo Bravo',
                'Malinaltepec',
                'Mártir de Cuilapan',
                'Metlatónoc',
                'Mochitlán',
                'Olinalá',
                'Ometepec',
                'Pedro Ascencio Alquisiras',
                'Petatlán',
                'Pilcaya',
                'Pungarabato',
                'Quechultenango',
                'San Luis Acatlán',
                'San Marcos',
                'San Miguel Totolapan',
                'Taxco de Alarcón',
                'Tecoanapa',
                'Técpan de Galeana',
                'Teloloapan',
                'Tepecoacuilco de Trujano',
                'Tetipac',
                'Tixtla de Comonfort',
                'Tlacoachistlahuaca',
                'Tlacoapa',
                'Tlalchapa',
                'Tlalixtaquilla de Maldonado',
                'Tlapa de Comonfort',
                'Tlapehuala',
                'La Unión de Isidoro Montes de Oca',
                'Xalpatláhuac',
                'Xochihuehuetlán',
                'Xochistlahuaca',
                'Zapotitlán Tablas',
                'Zirándaro de los Chávez',
                'Zitlala',
                'Las Vigas',
                'Ñuu Savi',
                'San Nicolás'
            ],
            'Hidalgo' => [
                'Acatlán',
                'Acaxochitlán',
                'Actopan',
                'Agua Blanca de Iturbide',
                'Ajacuba',
                'Alfajayucan',
                'Almoloya',
                'Apan',
                'Atitalaquia',
                'Atlapexco',
                'Atotonilco el Grande',
                'Atotonilco de Tula',
                'Calnali',
                'Cardonal',
                'Cuautepec de Hinojosa',
                'Chapantongo',
                'Chapulhuacán',
                'Chilcuautla',
                'El Arenal',
                'Eloxochitlán',
                'Emiliano Zapata',
                'Epazoyucan',
                'Francisco I. Madero',
                'Huasca de Ocampo',
                'Huautla',
                'Huazalingo',
                'Huehuetla',
                'Huejutla de Reyes',
                'Huichapan',
                'Ixmiquilpan',
                'Jacala de Ledezma',
                'Jaltocán',
                'Juárez Hidalgo',
                'La Misión',
                'Lolotla',
                'Metepec',
                'Metztitlán',
                'Mineral del Chico',
                'Mineral del Monte',
                'Mineral de la Reforma',
                'Mixquiahuala de Juárez',
                'Molango de Escamilla',
                'Nicolás Flores',
                'Nopala de Villagrán',
                'Omitlán de Juárez',
                'Pacula',
                'Pachuca de Soto',
                'Pisaflores',
                'Progreso de Obregón',
                'San Agustín Metzquititlán',
                'San Agustín Tlaxiaca',
                'San Bartolo Tutotepec',
                'San Felipe Orizatlán',
                'San Salvador',
                'Santiago de Anaya',
                'Santiago Tulantepec de Lugo Guerrero',
                'Singuilucan',
                'Tasquillo',
                'Tecozautla',
                'Tenango de Doria',
                'Tepeapulco',
                'Tepehuacán de Guerrero',
                'Tepeji del Río de Ocampo',
                'Tepetitlán',
                'Tetepango',
                'Tezontepec de Aldama',
                'Tianguistengo',
                'Tizayuca',
                'Tlahuelilpan',
                'Tlahuiltepa',
                'Tlanalapa',
                'Tlanchinol',
                'Tlaxcoapan',
                'Tolcayuca',
                'Tula de Allende',
                'Tulancingo de Bravo',
                'Villa de Tezontepec',
                'Xochiatipan',
                'Xochicoatlán',
                'Yahualica',
                'Zacualtipán de Ángeles',
                'Zapotlán de Juárez',
                'Zempoala',
                'Zimapán'
            ],
            'Jalisco' => [
                'Acatic',
                'Acatlán de Juárez',
                'Ahualulco de Mercado',
                'Amacueca',
                'Amatitán',
                'Ameca',
                'Arandas',
                'Atemajac de Brizuela',
                'Atengo',
                'Atenguillo',
                'Atotonilco el Alto',
                'Atoyac',
                'Autlán de Navarro',
                'Ayotlán',
                'Ayutla',
                'La Barca',
                'Bolaños',
                'Cabo Corrientes',
                'Casimiro Castillo',
                'Cihuatlán',
                'Zapotlán el Grande',
                'Cocula',
                'Colotlán',
                'Concepción de Buenos Aires',
                'Cuautitlán de García Barragán',
                'Cuautla',
                'Cuquío',
                'Chapala',
                'Chimaltitán',
                'Chiquilistlán',
                'Degollado',
                'Ejutla',
                'El Grullo',
                'El Limón',
                'El Salto',
                'Encarnación de Díaz',
                'Etzatlán',
                'Gómez Farías',
                'Guachinango',
                'Guadalajara',
                'Hostotipaquillo',
                'Huejúcar',
                'Huejuquilla el Alto',
                'La Huerta',
                'Ixtlahuacán de los Membrillos',
                'Ixtlahuacán del Río',
                'Jalostotitlán',
                'Jamay',
                'Jesús María',
                'Jilotlán de los Dolores',
                'Jocotepec',
                'Juanacatlán',
                'Juchitlán',
                'Lagos de Moreno',
                'El Arenal',
                'Magdalena',
                'Mezquitic',
                'Mixtlán',
                'Ocotlán',
                'Ojuelos de Jalisco',
                'Pihuamo',
                'Poncitlán',
                'Puerto Vallarta',
                'Villa Purificación',
                'Quitupan',
                'El Teúl',
                'San Cristóbal de la Barranca',
                'San Diego de Alejandría',
                'San Juan de los Lagos',
                'San Julián',
                'San Marcos',
                'San Martín de Bolaños',
                'San Martín Hidalgo',
                'San Miguel el Alto',
                'Gómez Farías',
                'San Sebastián del Oeste',
                'Santa María de los Ángeles',
                'Sayula',
                'Tala',
                'Talpa de Allende',
                'Tamazula de Gordiano',
                'Tapalpa',
                'Tecalitlán',
                'Techaluta de Montenegro',
                'Tenamaxtlán',
                'Teocaltiche',
                'Teocuitatlán de Corona',
                'Tepatitlán de Morelos',
                'Tequila',
                'Teuchitlán',
                'Tizapán el Alto',
                'Tlajomulco de Zúñiga',
                'San Pedro Tlaquepaque',
                'Tolimán',
                'Tomatlán',
                'Tonalá',
                'Tonaya',
                'Tonila',
                'Totatiche',
                'Tototlán',
                'Tuxcacuesco',
                'Tuxcueca',
                'Tuxpan',
                'Unión de San Antonio',
                'Unión de Tula',
                'Valle de Guadalupe',
                'Valle de Juárez',
                'San Gabriel',
                'Villa Corona',
                'Villa Guerrero',
                'Villa Hidalgo',
                'Cañadas de Obregón',
                'Yahualica de González Gallo',
                'Zacoalco de Torres',
                'Zapopan',
                'Zapotiltic',
                'Zapotitlán de Vadillo',
                'Zapotlán del Rey',
                'Zapotlanejo',
                'San Ignacio Cerro Gordo'
            ],
            'Michoacán' => [
                'Acuitzio',
                'Aguililla',
                'Álvaro Obregón',
                'Angamacutiro',
                'Angangueo',
                'Apatzingán',
                'Aporo',
                'Aquila',
                'Ario',
                'Arteaga',
                'Briseñas',
                'Buenavista',
                'Carácuaro',
                'Coahuayana',
                'Coalcomán de Vázquez Pallares',
                'Coeneo',
                'Contepec',
                'Copándaro',
                'Cotija',
                'Cuitzeo',
                'Charapan',
                'Charo',
                'Chavinda',
                'Cherán',
                'Chilchota',
                'Chinicuila',
                'Chucándiro',
                'Churintzio',
                'Churumuco',
                'Ecuandureo',
                'Epitacio Huerta',
                'Erongarícuaro',
                'Gabriel Zamora',
                'Hidalgo',
                'La Huacana',
                'Huandacareo',
                'Huaniqueo',
                'Huetamo',
                'Huiramba',
                'Indaparapeo',
                'Irimbo',
                'Ixtlán',
                'Jacona',
                'Jiménez',
                'Jiquilpan',
                'Juárez',
                'Jungapeo',
                'Lagunillas',
                'Madero',
                'Maravatío',
                'Marcos Castellanos',
                'Lázaro Cárdenas',
                'Morelia',
                'Morelos',
                'Múgica',
                'Nahuatzen',
                'Nocupétaro',
                'Nuevo Parangaricutiro',
                'Nuevo Urecho',
                'Numarán',
                'Ocampo',
                'Pajacuarán',
                'Panindícuaro',
                'Parácuaro',
                'Paracho',
                'Pátzcuaro',
                'Penjamillo',
                'Peribán',
                'La Piedad',
                'Purépero',
                'Puruándiro',
                'Queréndaro',
                'Quiroga',
                'Cojumatlán de Régules',
                'Los Reyes',
                'Sahuayo',
                'San Lucas',
                'Santa Ana Maya',
                'Salvador Escalante',
                'Senguio',
                'Susupuato',
                'Tacámbaro',
                'Tancítaro',
                'Tangamandapio',
                'Tangancícuaro',
                'Tanhuato',
                'Taretan',
                'Tarímbaro',
                'Tepalcatepec',
                'Tingambato',
                'Tingüindín',
                'Tiquicheo de Nicolás Romero',
                'Tlalpujahua',
                'Tlazazalca',
                'Tocumbo',
                'Tumbiscatío',
                'Turicato',
                'Tuxpan',
                'Tuzantla',
                'Tzintzuntzan',
                'Tzitzio',
                'Uruapan',
                'Venustiano Carranza',
                'Villamar',
                'Vista Hermosa',
                'Yurécuaro',
                'Zacapu',
                'Zamora',
                'Zináparo',
                'Zinapécuaro',
                'Ziracuaretiro',
                'Zitácuaro',
                'José Sixto Verduzco'
            ],
            'Morelos' => [
                'Amacuzac',
                'Atlatlahucan',
                'Axochiapan',
                'Ayala',
                'Coatetelco',
                'Coatlán del Río',
                'Cuautla',
                'Cuernavaca',
                'Emiliano Zapata',
                'Hueyapan',
                'Huitzilac',
                'Jantetelco',
                'Jiutepec',
                'Jojutla',
                'Jonacatepec de Leandro Valle',
                'Mazatepec',
                'Miacatlán',
                'Ocuituco',
                'Puente de Ixtla',
                'Temixco',
                'Temoac',
                'Tepalcingo',
                'Tepoztlán',
                'Tetecala',
                'Tetela del Volcán',
                'Tlalnepantla',
                'Tlaltizapán de Zapata',
                'Tlaquiltenango',
                'Tlayacapan',
                'Totolapan',
                'Xochitepec',
                'Xoxocotla',
                'Yautepec',
                'Yecapixtla',
                'Zacatepec',
                'Zacualpan de Amilpas'
            ],
            'Nayarit' => [
                'Acaponeta',
                'Ahuacatlán',
                'Amatlán de Cañas',
                'Bahía de Banderas',
                'Compostela',
                'Del Nayar',
                'Huajicori',
                'Ixtlán del Río',
                'Jala',
                'La Yesca',
                'Rosamorada',
                'Ruiz',
                'San Blas',
                'San Pedro Lagunillas',
                'Santa María del Oro',
                'Santiago Ixcuintla',
                'Tecuala',
                'Tepic',
                'Tuxpan',
                'Xalisco'
            ],
            'Nuevo León' => [
                'Abasolo',
                'Agualeguas',
                'Allende',
                'Anáhuac',
                'Apodaca',
                'Aramberri',
                'Bustamante',
                'Cadereyta Jiménez',
                'Cerralvo',
                'Ciénega de Flores',
                'China',
                'Doctor Arroyo',
                'Doctor Coss',
                'Doctor González',
                'El Carmen',
                'Galeana',
                'García',
                'General Bravo',
                'General Escobedo',
                'General Terán',
                'General Treviño',
                'General Zaragoza',
                'General Zuazua',
                'Guadalupe',
                'Hidalgo',
                'Higueras',
                'Hualahuises',
                'Iturbide',
                'Juárez',
                'Lampazos de Naranjo',
                'Linares',
                'Los Aldamas',
                'Los Herreras',
                'Los Ramones',
                'Marín',
                'Melchor Ocampo',
                'Mier y Noriega',
                'Mina',
                'Montemorelos',
                'Monterrey',
                'Parás',
                'Pesquería',
                'Rayones',
                'Sabinas Hidalgo',
                'Salinas Victoria',
                'San Nicolás de los Garza',
                'San Pedro Garza García',
                'Santa Catarina',
                'Santiago',
                'Vallecillo',
                'Villaldama'
            ],
            'Oaxaca' => [
                'Abejones',
                'Acatlán de Pérez Figueroa',
                'Asunción Cacalotepec',
                'Asunción Cuyotepeji',
                'Asunción Ixtaltepec',
                'Asunción Nochixtlán',
                'Asunción Ocotlán',
                'Asunción Tlacolulita',
                'Ayotzintepec',
                'El Barrio de la Soledad',
                'Calihualá',
                'Candelaria Loxicha',
                'Ciénega de Zimatlán',
                'Ciudad Ixtepec',
                'Coatecas Altas',
                'Coicoyán de las Flores',
                'Concepción Buenavista',
                'Concepción Pápalo',
                'Constancia del Rosario',
                'Cosolapa',
                'Cosoltepec',
                'Cuilápam de Guerrero',
                'Cuyamecalco Villa de Zaragoza',
                'Chahuites',
                'Chalcatongo de Hidalgo',
                'Chiquihuitlán de Benito Juárez',
                'Heroica Ciudad de Ejutla de Crespo',
                'Heroica Ciudad de Huajuapan de León',
                'Heroica Ciudad de Juchitán de Zaragoza',
                'Heroica Ciudad de Tlaxiaco',
                'San Juan Bautista Tuxtepec'
            ],
            'Puebla' => [
                'Acajete',
                'Acateno',
                'Acatlán',
                'Acatzingo',
                'Acteopan',
                'Ahuacatlán',
                'Ahuatlán',
                'Ahuazotepec',
                'Ahuehuetitla',
                'Ajalpan',
                'Albino Zertuche',
                'Aljojuca',
                'Altepexi',
                'Amatlán',
                'Amozoc',
                'Aquixtla',
                'Atempan',
                'Atexcal',
                'Atlixco',
                'Atoyatempan',
                'Atzala',
                'Atzitzihuacán',
                'Atzitzintla',
                'Axutla',
                'Ayotoxco de Guerrero',
                'Atlequizayán',
                'Calpan',
                'Caltepec',
                'Camocuautla',
                'Cañada Morelos',
                'Caxhuacan',
                'Coatepec',
                'Coatzingo',
                'Cohetzala',
                'Cohuecan',
                'Coronango',
                'Coxcatlán',
                'Coyomeapan',
                'Coyotepec',
                'Cuapiaxtla de Madero',
                'Cuautempan',
                'Cuautinchán',
                'Cuautlancingo',
                'Cuayuca de Andrade',
                'Cuetzalan del Progreso',
                'Cuyoaco',
                'Chalchicomula de Sesma',
                'Chapulco',
                'Chiautla',
                'Chiautzingo',
                'Chiconcuautla',
                'Chichiquila',
                'Chietla',
                'Chigmecatitlán',
                'Chignahuapan',
                'Chignautla',
                'Chila',
                'Chila de la Sal',
                'Chilchotla',
                'Chinantla',
                'Domingo Arenas',
                'Eloxochitlán',
                'Epatlán',
                'Esperanza',
                'Francisco Z. Mena',
                'General Felipe Ángeles',
                'Guadalupe',
                'Guadalupe Victoria',
                'Hermenegildo Galeana',
                'Honey',
                'Huaquechula',
                'Huatlatlauca',
                'Huauchinango',
                'Huehuetla',
                'Huehuetlán el Chico',
                'Huehuetlán el Grande',
                'Huejotzingo',
                'Hueyapan',
                'Hueytamalco',
                'Hueytlalpan',
                'Huitzilan de Serdán',
                'Huitziltepec',
                'Ixcamilpa de Guerrero',
                'Ixcaquixtla',
                'Ixtacamaxtitlán',
                'Ixtepec',
                'Izúcar de Matamoros',
                'Jalpan',
                'Jolalpan',
                'Jonotla',
                'Jopala',
                'Juan C. Bonilla',
                'Juan Galindo',
                'Juan N. Méndez',
                'Lafragua',
                'Libres',
                'La Magdalena Tlatlauquitepec',
                'Mazapiltepec de Juárez',
                'Mixtla',
                'Molcaxac',
                'Naupan',
                'Nauzontla',
                'Nealtican',
                'Nicolás Bravo',
                'Nopalucan',
                'Ocotepec',
                'Ocoyucan',
                'Olintla',
                'Oriental',
                'Pahuatlán',
                'Palmar de Bravo',
                'Pantepec',
                'Petlalcingo',
                'Piaxtla',
                'Puebla',
                'Quecholac',
                'Quimixtlán',
                'Rafael Lara Grajales',
                'Reyes de Juárez',
                'San Andrés Cholula',
                'San Antonio Cañada',
                'San Diego la Mesa Tochimiltzingo',
                'San Felipe Teotlalcingo',
                'San Felipe Tepatlán',
                'San Gabriel Chilac',
                'San Gregorio Atzompa',
                'San Jerónimo Tecuanipan',
                'San Jerónimo Xayacatlán',
                'San José Chiapa',
                'San José Miahuatlán',
                'San Juan Atenco',
                'San Juan Atzompa',
                'San Martín Texmelucan',
                'San Martín Totoltepec',
                'San Matías Tlalancaleca',
                'San Miguel Ixitlán',
                'San Miguel Xoxtla',
                'San Nicolás Buenos Aires',
                'San Nicolás de los Ranchos',
                'San Pablo Anicano',
                'San Pedro Cholula',
                'San Pedro Yeloixtlahuaca',
                'San Salvador el Seco',
                'San Salvador el Verde',
                'San Salvador Huixcolotla',
                'San Sebastián Tlacotepec',
                'Santa Catarina Tlaltempan',
                'Santa Inés Ahuatempan',
                'Santa Isabel Cholula',
                'Santiago Miahuatlán',
                'Santo Tomás Hueyotlipan',
                'Soltepec',
                'Tecali de Herrera',
                'Tecamachalco',
                'Tecomatlán',
                'Tehuacán',
                'Tehuitzingo',
                'Tenampulco',
                'Teopantlán',
                'Teotlalco',
                'Tepanco de López',
                'Tepango de Rodríguez',
                'Tepatlaxco de Hidalgo',
                'Tepeaca',
                'Tepemaxalco',
                'Tepeojuma',
                'Tepetzintla',
                'Tepexco',
                'Tepexi de Rodríguez',
                'Tepeyahualco',
                'Tepeyahualco de Cuauhtémoc',
                'Tetela de Ocampo',
                'Teteles de Ávila Castillo',
                'Teziutlán',
                'Tianguismanalco',
                'Tilapa',
                'Tlacotepec de Benito Juárez',
                'Tlacuilotepec',
                'Tlachichuca',
                'Tlahuapan',
                'Tlaltenango',
                'Tlanepantla',
                'Tlaola',
                'Tlapacoya',
                'Tlapanalá',
                'Tlatlauquitepec',
                'Tlaxco',
                'Tochimilco',
                'Tochtepec',
                'Totoltepec de Guerrero',
                'Tulcingo',
                'Tuzamapan de Galeana',
                'Tzicatlacoyan',
                'Venustiano Carranza',
                'Vicente Guerrero',
                'Xayacatlán de Bravo',
                'Xicotepec',
                'Xicotlán',
                'Xiutetelco',
                'Xochiapulco',
                'Xochiltepec',
                'Xochitlán de Vicente Suárez',
                'Xochitlán Todos Santos',
                'Yaonáhuac',
                'Yehualtepec',
                'Zacapala',
                'Zacapoaxtla',
                'Zacatlán',
                'Zapotitlán',
                'Zapotitlán de Méndez',
                'Zaragoza',
                'Zautla',
                'Zihuateutla',
                'Zinacatepec',
                'Zongozotla',
                'Zoquiapan',
                'Zoquitlán'
            ],
            'Querétaro' => [
                'Amealco de Bonfil',
                'Pinal de Amoles',
                'Arroyo Seco',
                'Cadereyta de Montes',
                'Colón',
                'Corregidora',
                'Ezequiel Montes',
                'Huimilpan',
                'Jalpan de Serra',
                'Landa de Matamoros',
                'El Marqués',
                'Pedro Escobedo',
                'Peñamiller',
                'Querétaro',
                'San Joaquín',
                'San Juan del Río',
                'Tequisquiapan',
                'Tolimán'
            ],
            'Quintana Roo' => [
                'Othón P. Blanco',
                'Benito Juárez',
                'Felipe Carrillo Puerto',
                'José María Morelos',
                'Lázaro Cárdenas',
                'Cozumel',
                'Isla Mujeres',
                'Playa del Carmen',
                'Tulum',
                'Bacalar',
                'Puerto Morelos'
            ],
            'San Luis Potosí' => [
                'Ahualulco',
                'Alaquines',
                'Aquismón',
                'Armadillo de los Infante',
                'Axtla de Terrazas',
                'Cárdenas',
                'Catorce',
                'Cedral',
                'Cerritos',
                'Cerro de San Pedro',
                'Charcas',
                'Ciudad del Maíz',
                'Ciudad Fernández',
                'Ciudad Valles',
                'Coxcatlán',
                'Ébano',
                'El Naranjo',
                'Guadalcázar',
                'Huehuetlán',
                'Lagunillas',
                'Matehuala',
                'Matlapa',
                'Mexquitic de Carmona',
                'Moctezuma',
                'Rayón',
                'Rioverde',
                'Salinas',
                'San Antonio',
                'San Ciro de Acosta',
                'San Luis Potosí',
                'San Martín Chalchicuautla',
                'San Nicolás Tolentino',
                'San Vicente Tancuayalab',
                'Santa Catarina',
                'Santa María del Río',
                'Santo Domingo',
                'Soledad de Graciano Sánchez',
                'Tamasopo',
                'Tamazunchale',
                'Tampacán',
                'Tampamolón Corona',
                'Tancanhuitz de Santos',
                'Tanlajás',
                'Tanquián de Escobedo',
                'Tamuín',
                'Tierra Nueva',
                'Vanegas',
                'Venado',
                'Villa de Arriaga',
                'Villa de Arista',
                'Villa de Guadalupe',
                'Villa de la Paz',
                'Villa de Ramos',
                'Villa de Reyes',
                'Villa Hidalgo',
                'Villa Juárez',
                'Xilitla',
                'Zaragoza'
            ],
            'Sinaloa' => [
                'Ahome',
                'Angostura',
                'Badiraguato',
                'Concordia',
                'Cosalá',
                'Culiacán',
                'Choix',
                'Elota',
                'Escuinapa',
                'El Fuerte',
                'Guasave',
                'Mazatlán',
                'Mocorito',
                'Rosario',
                'Salvador Alvarado',
                'San Ignacio',
                'Sinaloa',
                'Navolato',
                'Eldorado',
                'Juan José Ríos'
            ],
            'Sonora' => [
                'Aconchi',
                'Agua Prieta',
                'Álamos',
                'Altar',
                'Arivechi',
                'Arizpe',
                'Átil',
                'Bacadéhuachi',
                'Bacanora',
                'Bacerac',
                'Bacoachi',
                'Bácum',
                'Banámichi',
                'Baviácora',
                'Bavispe',
                'Benjamín Hill',
                'Caborca',
                'Cajeme',
                'Cananea',
                'Carbó',
                'La Colorada',
                'Cucurpe',
                'Cumpas',
                'Divisaderos',
                'Empalme',
                'Etchojoa',
                'Fronteras',
                'Granados',
                'Guaymas',
                'Hermosillo',
                'Huachinera',
                'Huásabas',
                'Huatabampo',
                'Huépac',
                'Ímuris',
                'Magdalena',
                'Mazatán',
                'Moctezuma',
                'Naco',
                'Nácori Chico',
                'Nacozari de García',
                'Navojoa',
                'Nogales',
                'Ónavas',
                'Opodepe',
                'Oquitoa',
                'Pitiquito',
                'Puerto Peñasco',
                'Quiriego',
                'Rayón',
                'Rosario',
                'Sahuaripa',
                'San Felipe de Jesús',
                'San Javier',
                'San Luis Río Colorado',
                'San Miguel de Horcasitas',
                'San Pedro de la Cueva',
                'Santa Ana',
                'Santa Cruz',
                'Sáric',
                'Soyopa',
                'Suaqui Grande',
                'Tepache',
                'Trincheras',
                'Tubutama',
                'Ures',
                'Villa Hidalgo',
                'Villa Pesqueira',
                'Yécora',
                'General Plutarco Elías Calles',
                'Benito Juárez',
                'San Ignacio Río Muerto'
            ],
            'Tabasco' => [
                'Balancán',
                'Cárdenas',
                'Centla',
                'Centro',
                'Comalcalco',
                'Cunduacán',
                'Emiliano Zapata',
                'Huimanguillo',
                'Jalapa',
                'Jalpa de Méndez',
                'Jonuta',
                'Macuspana',
                'Nacajuca',
                'Paraíso',
                'Tacotalpa',
                'Teapa',
                'Tenosique'
            ],
            'Tamaulipas' => [
                'Abasolo',
                'Aldama',
                'Altamira',
                'Antiguo Morelos',
                'Burgos',
                'Bustamante',
                'Camargo',
                'Casas',
                'Ciudad Madero',
                'Cruillas',
                'Gómez Farías',
                'González',
                'Güémez',
                'Guerrero',
                'Gustavo Díaz Ordaz',
                'Hidalgo',
                'Jaumave',
                'Jiménez',
                'Llera',
                'Mainero',
                'El Mante',
                'Matamoros',
                'Méndez',
                'Mier',
                'Miguel Alemán',
                'Miquihuana',
                'Nuevo Laredo',
                'Nuevo Morelos',
                'Ocampo',
                'Padilla',
                'Palmillas',
                'Reynosa',
                'Río Bravo',
                'San Carlos',
                'San Fernando',
                'San Nicolás',
                'Soto la Marina',
                'Tampico',
                'Tula',
                'Valle Hermoso',
                'Victoria',
                'Villagrán',
                'Xicoténcatl'
            ],
            'Tlaxcala' => [
                'Acuamanala de Miguel Hidalgo',
                'Amaxac de Guerrero',
                'Apetatitlán de Antonio Carvajal',
                'Apizaco',
                'Atlangatepec',
                'Altzayanca',
                'Benito Juárez',
                'Calpulalpan',
                'Contla de Juan Cuamatzi',
                'Cuapiaxtla',
                'Cuaxomulco',
                'Chiautempan',
                'Emiliano Zapata',
                'Españita',
                'Huamantla',
                'Hueyotlipan',
                'Ixtacuixtla de Mariano Matamoros',
                'Ixtenco',
                'La Magdalena Tlaltelulco',
                'Mazatecochco de José María Morelos',
                'Muñoz de Domingo Arenas',
                'Nativitas',
                'Nanacamilpa de Mariano Arista',
                'Panotla',
                'Papalotla de Xicohténcatl',
                'San Damián Texoloc',
                'San Francisco Tetlanohcan',
                'San Jerónimo Zacualpan',
                'San José Teacalco',
                'San Juan Huactzinco',
                'San Lorenzo Axocomanitla',
                'San Lucas Tecopilco',
                'San Pablo del Monte',
                'Santa Ana Nopalucan',
                'Santa Apolonia Teacalco',
                'Santa Catarina Ayometla',
                'Santa Cruz Tlaxcala',
                'Santa Isabel Xiloxoxtla',
                'Sanctorum de Lázaro Cárdenas',
                'Tenancingo',
                'Teolocholco',
                'Tepeyanco',
                'Tepetitla de Lardizábal',
                'Terrenate',
                'Tetla de la Solidaridad',
                'Tetlatlahuca',
                'Tlaxcala',
                'Tlaxco',
                'Tocatlán',
                'Tocatlán',
                'Totolac',
                'Tzompantepec',
                'Xaloztoc',
                'Xaltocan',
                'Xicohtzinco',
                'Yauhquemehcan',
                'Zacatelco'
            ],
            'Veracruz' => [
                'Acajete',
                'Acatlán',
                'Acayucan',
                'Actopan',
                'Acula',
                'Acultzingo',
                'Camarón de Tejeda',
                'Alpatláhuac',
                'Alto Lucero de Gutiérrez Barrios',
                'Altotonga',
                'Alvarado',
                'Amatitlán',
                'Naranjos Amatlán',
                'Amatlán de los Reyes',
                'Ángel R. Cabada',
                'La Antigua',
                'Apazapan',
                'Aquila',
                'Astacinga',
                'Atlahuilco',
                'Atoyac',
                'Atzacan',
                'Atzalan',
                'Tlaltetela',
                'Ayahualulco',
                'Banderilla',
                'Benito Juárez',
                'Boca del Río',
                'Calcahualco',
                'Camerino Z. Mendoza',
                'Carrillo Puerto',
                'Catemaco',
                'Cazones de Herrera',
                'Cerro Azul',
                'Citlaltépetl',
                'Coacoatzintla',
                'Coahuitlán',
                'Coatepec',
                'Coatzacoalcos',
                'Coatzintla',
                'Coetzala',
                'Colipa',
                'Comapa',
                'Córdoba',
                'Cosamaloapan de Carpio',
                'Cosautlán de Carvajal',
                'Coscomatepec',
                'Cosoleacaque',
                'Cotaxtla',
                'Coxquihui',
                'Coyutla',
                'Cuichapa',
                'Cuitláhuac',
                'Chacaltianguis',
                'Chalma',
                'Chiconamel',
                'Chiconquiaco',
                'Chicontepec',
                'Chinameca',
                'Chinampa de Gorostiza',
                'Las Choapas',
                'Chocamán',
                'Chontla',
                'Chumatlán',
                'Emiliano Zapata',
                'Espinal',
                'Filomeno Mata',
                'Fortín',
                'Gutiérrez Zamora',
                'Hidalgotitlán',
                'Huatusco',
                'Huayacocotla',
                'Hueyapan de Ocampo',
                'Huiloapan de Cuauhtémoc',
                'Ignacio de la Llave',
                'Ilamatlán',
                'Isla',
                'Ixcatepec',
                'Ixhuacán de los Reyes',
                'Ixhuatlán del Café',
                'Ixhuatlancillo',
                'Ixhuatlán del Sureste',
                'Ixhuatlán de Madero',
                'Ixmatlahuacan',
                'Ixtaczoquitlán',
                'Jalacingo',
                'Xalapa',
                'Jalcomulco',
                'Jáltipan',
                'Jamapa',
                'Jesús Carranza',
                'Xico',
                'Jilotepec',
                'Juan Rodríguez Clara',
                'Juchique de Ferrer',
                'Landero y Coss',
                'Lerdo de Tejada',
                'Magdalena',
                'Maltrata',
                'Manlio Fabio Altamirano',
                'Mariano Escobedo',
                'Martínez de la Torre',
                'Mecatlán',
                'Mecayapan',
                'Medellín',
                'Miahuatlán',
                'Las Minas',
                'Minatitlán',
                'Misantla',
                'Mixtla de Altamirano',
                'Moloacán',
                'Naolinco',
                'Naranjal',
                'Naranjos Amatlán',
                'Nautla',
                'Nogales',
                'Oluta',
                'Omealca',
                'Orizaba',
                'Otatitlán',
                'Oteapan',
                'Ozuluama de Mascareñas',
                'Pajapan',
                'Pánuco',
                'Papantla',
                'Paso del Macho',
                'Paso de Ovejas',
                'La Perla',
                'Perote',
                'Platón Sánchez',
                'Playa Vicente',
                'Poza Rica de Hidalgo',
                'Las Vigas de Ramírez',
                'Pueblo Viejo',
                'Puente Nacional',
                'Rafael Delgado',
                'Rafael Lucio',
                'Los Reyes',
                'Río Blanco',
                'Saltabarranca',
                'San Andrés Tenejapan',
                'San Andrés Tuxtla',
                'San Juan Evangelista',
                'Santiago Tuxtla',
                'Sayula de Alemán',
                'Soconusco',
                'Sochiapa',
                'Soledad Atzompa',
                'Soledad de Doblado',
                'Soteapan',
                'Tamalín',
                'Tamiahua',
                'Tampico Alto',
                'Tancoco',
                'Tantima',
                'Tantoyuca',
                'Tatatila',
                'Castillo de Teayo',
                'Tecolutla',
                'Tehuipango',
                'Álamo Temapache',
                'Tempoal',
                'Tenampa',
                'Tenochtitlán',
                'Teocelo',
                'Tepatlaxco',
                'Tepetlán',
                'Tepetzintla',
                'Tequila',
                'José Azueta',
                'Texcatepec',
                'Texhuacán',
                'Texistepec',
                'Tezonapa',
                'Tierra Blanca',
                'Tihuatlán',
                'Tlacojalpan',
                'Tlacolulan',
                'Tlacotalpan',
                'Tlacotepec de Mejía',
                'Tlachichilco',
                'Tlalixcoyan',
                'Tlalnelhuayocan',
                'Tlapacoyan',
                'Tlaquilpa',
                'Tlilapan',
                'Tomatlán',
                'Tonayán',
                'Totutla',
                'Tuxpan',
                'Tuxtilla',
                'Úrsulo Galván',
                'Vega de Alatorre',
                'Veracruz',
                'Villa Aldama',
                'Xoxocotla',
                'Yanga',
                'Yecuatla',
                'Zacualpan',
                'Zaragoza',
                'Zentla',
                'Zongolica',
                'Zontecomatlán de López y Fuentes',
                'Zozocolco de Hidalgo',
                'Agua Dulce',
                'El Higo',
                'Nanchital de Lázaro Cárdenas del Río',
                'Tres Valles',
                'Carlos A. Carrillo',
                'Tatahuicapan de Juárez',
                'Uxpanapa',
                'San Rafael',
                'Santiago Sochiapan'
            ],
            'Yucatán' => [
                'Abalá',
                'Acanceh',
                'Akil',
                'Baca',
                'Bokobá',
                'Buctzotz',
                'Cacalchén',
                'Calotmul',
                'Cansahcab',
                'Cantamayec',
                'Celestún',
                'Cenotillo',
                'Conkal',
                'Cuncunul',
                'Cuzamá',
                'Chacsinkín',
                'Chankom',
                'Chapab',
                'Chemax',
                'Chicxulub Pueblo',
                'Chichimilá',
                'Chikindzonot',
                'Chocholá',
                'Chumayel',
                'Dzán',
                'Dzemul',
                'Dzidzantún',
                'Dzilam de Bravo',
                'Dzilam González',
                'Dzitás',
                'Dzoncauich',
                'Espita',
                'Halachó',
                'Hocabá',
                'Hoctún',
                'Homún',
                'Huhí',
                'Hunucmá',
                'Ixil',
                'Izamal',
                'Kanasín',
                'Kantunil',
                'Kaua',
                'Kinchil',
                'Kopomá',
                'Mama',
                'Maní',
                'Maxcanú',
                'Mayapán',
                'Mérida',
                'Mocochá',
                'Motul',
                'Muna',
                'Muxupip',
                'Opichén',
                'Oxkutzcab',
                'Panabá',
                'Peto',
                'Progreso',
                'Río Lagartos',
                'Sacalum',
                'Samahil',
                'Sanahcat',
                'San Felipe',
                'Santa Elena',
                'Seyé',
                'Sinanché',
                'Sotuta',
                'Sucilá',
                'Sudzal',
                'Suma',
                'Tahdziú',
                'Tahmek',
                'Teabo',
                'Tecoh',
                'Tekal de Venegas',
                'Tekantó',
                'Tekax',
                'Tekit',
                'Tekom',
                'Telchac Pueblo',
                'Telchac Puerto',
                'Temax',
                'Temozón',
                'Tepakán',
                'Tetiz',
                'Teya',
                'Ticul',
                'Timucuy',
                'Tinum',
                'Tixcacalcupul',
                'Tixkokob',
                'Tixméhuac',
                'Tixpéhual',
                'Tizimín',
                'Tunkás',
                'Tzucacab',
                'Uayma',
                'Ucú',
                'Umán',
                'Valladolid',
                'Xocchel',
                'Yaxcabá',
                'Yaxkukul',
                'Yobaín'
            ],
            'Zacatecas' => [
                'Apozol',
                'Apulco',
                'Atolinga',
                'Benito Juárez',
                'Calera',
                'Cañitas de Felipe Pescador',
                'Concepción del Oro',
                'Cuauhtémoc',
                'Chalchihuites',
                'Fresnillo',
                'Trinidad García de la Cadena',
                'Genaro Codina',
                'General Enrique Estrada',
                'General Francisco R. Murguía',
                'General Pánfilo Natera',
                'Guadalupe',
                'Huanusco',
                'Jalpa',
                'Jerez',
                'Jiménez del Teul',
                'Juan Aldama',
                'Juchipila',
                'Loreto',
                'Luis Moya',
                'Mazapil',
                'Melchor Ocampo',
                'Mezquital del Oro',
                'Miguel Auza',
                'Momax',
                'Monte Escobedo',
                'Morelos',
                'Moyahua de Estrada',
                'Nochistlán de Mejía',
                'Noria de Ángeles',
                'Ojocaliente',
                'Pánuco',
                'Pinos',
                'Río Grande',
                'Sain Alto',
                'El Salvador',
                'Sombrerete',
                'Susticacán',
                'Tabasco',
                'Tepechitlán',
                'Tepetongo',
                'Teúl de González Ortega',
                'Tlaltenango de Sánchez Román',
                'Valparaíso',
                'Vetagrande',
                'Villa de Cos',
                'Villa García',
                'Villa González Ortega',
                'Villa Hidalgo',
                'Villanueva',
                'Zacatecas',
                'Trancoso',
                'Santa María de la Paz'
            ],
        ];

        foreach ($municipalities as $state => $municipalityList) {
            foreach ($municipalityList as $municipality) {
                \App\Models\Municipality::create([
                    'name' => $municipality,
                    'id_state' => \App\Models\State::where('name', $state)->first()->id,
                ]);
            }
        }
    }
}
