name: Laravel
on: [pull_request]
jobs:
  laravel:
    name: Laravel
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql

      #- name: Composer Github auth
      #  run: composer config --global github-oauth.github.com ${{ secrets.GH_TOKEN }}

      - name: Install composer dependencies
        run: composer install

      - name: Copy env file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Migrate database
        run: php artisan migrate

      - name: Run seeders
        run: php artisan db:seed

      - name: Duster Lint
        run: ./vendor/bin/duster lint

      - name: Run tests
        run: php artisan test --stop-on-failure=false --colors=never
